from .builders.point import Point
from .builders.line import Line
from .builders.shape2 import Shape
from .figures.rectangle import Rectangle
from .figures.square import Square
from .figures.triangle import Triangle
from .figures.triangles.equilateral import Equilateral
from .figures.triangles.trirectangle import TriRectangle
from .figures.triangles.isosceles import Isosceles
from .figures.triangles.scalene import Scalene
